### PR TITLE
Run 32-bit tests

### PR DESCRIPTION
**Pull request by qmfrederik**
Run tests on 32-bit .NET on Windows.

### CODE REVIEW

**Comment by qmfrederik** [comment]
The crash during the 32-bit test is probably https://github.com/libgit2/libgit2sharp/issues/1755 (https://github.com/libgit2/libgit2/issues/5363#issuecomment-578071656), likely fixed by https://github.com/libgit2/libgit2sharp/commit/b78b2900dfe3dc835e0e79f6e542672826bdbc9a

**Comment by AArnott** [comment]
@qmfrederik Any fixes are going to the `v3.4` branch. `master` is for future feature development. 
Consider rebasing and targeting `v3.4` if this is to fix a bug or add tests that should pass on v3.4.

**Comment by qmfrederik** [comment]
@AArnott Roger that, I'll rebase once #633 gets in.

**Review by AArnott — APPROVED** [review]
Looks good. I'm rebasing on v3.4 (actually on your other PR) so we can get this goodness into v3.4.

**Pull request merged**
