### PR TITLE
Profile benchmarks

### PR DESCRIPTION
**Pull request by qmfrederik**
This PR attempts to add profiling to the benchmark runs. Let's see how it goes.

### CODE REVIEW

**Comment by AArnott** [comment]
It looks like you may be close. :)

As profiling impacts the runtime perf, and we generally just want to measure perf, ideally this change can be under a pipeline parameter so we can check the box to profile a build where without that it just does the normal thing.

**Comment by qmfrederik** [comment]
Looks like we're seeing https://github.com/dotnet/BenchmarkDotNet/issues/1731, so I used a preview version of BenchmarkDotNet. The AppVeyor package feed doesn't produce signed packages, though, so I had to disable package signature validation.

Let me see if I can get profiling to work at all, and worry about the NuGet configuration later 😄 .

**Comment by qmfrederik** [comment]
So it looks like this actually gets some profiling done and creates SpeedScope files. But https://speedscope.app/ barks at them:

> Unrecognized format! See documentation about supported formats.

Thoughts?

**Comment by AArnott** [comment]
I've never heard of speedscope files, so I'm afraid I can't offer help there. But it sounds like progress. :)

**Pull request closed without merging**
