### PR TITLE
Fix resolving HEAD reference if it's a packed ref

### LINKED ISSUE #602: Regression: Nerdbank.GitVersioning.GitException: The commit 0000000000000000000000000000000000000000 was not found in this repository.
Hello, I ran into a problem with the managed git implementation in nbgv (`3.4.194`).
The `3.3.37` version works fine.

```sh
> cat .git/HEAD
ref: refs/heads/my/build_system_setup

> dotnet nbgv get-version
 Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Nerdbank.GitVersioning.GitException: The commit 0000000000000000000000000000000000000000 was not found in this repository.
     at Nerdbank.GitVersioning.ManagedGit.GitRepository.GetCommit(GitObjectId sha, Boolean readAuthor)
     at Nerdbank.GitVersioning.Managed.ManagedGitContext.TrySelectCommit(String committish)
     at Nerdbank.GitVersioning.Tool.Program.OnGetVersionCommand(String project, IReadOnlyList`1 metadata, String format, String variable, String commitIsh) in D:\a\1\s\src\nbgv\Program.cs:line 371
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at System.Delegate.DynamicInvokeImpl(Object[] args)
     at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
     at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseMiddleware>b__0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

The repo was cloned through git alternates and then repacked.

```sh
git repack -a -d && rm -rf .git/objects/info/alternates
```

### PR DESCRIPTION
**Pull request by filipnavara**
The issue is that we have a repository that has HEAD pointing containing `ref: refs/heads/netcore/master`. All references are packed so to resolve `refs/heads/netcore/master` it's necessary to looking into the packed refs and not just on the file system.

Fixes #602

### CODE REVIEW

**Comment by filipnavara** [comment]
Eh, looks like the fix will need a bit of tweaking. At least we know the underlying cause though :)

**Comment by AArnott** [comment]
Thanks for contributing, and especially for the repro steps. Are you planning to add the test case or should I find some time to do that?

**Comment by AArnott** [comment]
Also, we need to rebase your PR to the `v3.4` branch since we need to fix that version, and `master` targets `v3.5`. Would you like to do that or shall I and force-push to your source branch?

**Comment by filipnavara** [comment]
You will likely have better idea how to structure the test case than me so I would prefer if you look into it. I've uploaded an example repository in the linked issue so it should be fairly trivial to incorporate it somehow.

Feel free to push to the branch as much as necessary. I can rebase it on top of the 3.4 branch but at the moment I am not anywhere near a computer 😅

It also got me thinking that aside from the actual problem that I fixed it would have been reasonable to update GetBuildVersion to either fail or at least issue a warning in the MSBuild task. Now it silently produces a version without the GIT fields in `ThisAssembly` and with the base version instead of the calculated one.

**Comment by filipnavara** [comment]
Thanks!

**Comment by AArnott** [comment]
Thank you very much for contributing the fix!

**Pull request merged**
