### PR TITLE
Allow use of `NBGV_SetMauiVersionProperties` to suppress new behavior

### PR DESCRIPTION
**Pull request by AArnott**
Fixes issue @bakerhillpins brought up in https://github.com/dotnet/Nerdbank.GitVersioning/issues/828#issuecomment-1301098701

### CODE REVIEW

**Comment by bakerhillpins** [comment]
@AArnott  This change allows the user to opt out of BOTH settings at once which is convenient when one is using central package management and they don't want to apply it to their EXE project.

It also appears that this feature is OFF by default as I don't see any change where `NBGV_SetMauiVersionProperties` is set to true.  Thus users would need to Opt IN to version updates?
Was your plan to opt in or out? My thought would be that users would expect oping out.

**Comment by AArnott** [comment]
This is written to allow users to opt out. It remains on by default.
Note the check is that the new property _not_ be `false`. No one sets it to `false`, so the condition is satisfied and the behavior is _on_. Opting _out_ would look like this:

```xml
<NBGV_SetMauiVersionProperties>false</NBGV_SetMauiVersionProperties>
```

or

```
msbuild /p:NBGV_SetMauiVersionProperties=false
```

**Comment by bakerhillpins** [comment]
Thanks for the clarification and sorry about the confusion.  I thought undefined properties evaluated false but I can't find the documentation concerning that. LOL

**Comment by AArnott** [comment]
msbuild properties are not boolean. They are all strings. They default to evaluating to the empty string.

**Pull request merged**
